receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

exporters:
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp/"
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
  otlp/tempo:
    endpoint: tempo:3201
    tls:
      insecure: true
  # to view what's coming in/going out in the otel-collector logs
  # debug:
  #   verbosity: detailed

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s
  memory_limiter:
    check_interval: 1s
    limit_mib: 150
    spike_limit_mib: 50
  resourcedetection:
    detectors: [env, system]
    timeout: 2s

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlphttp/prometheus] #[otlphttp/prometheus, debug]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlp/tempo] #[otlp/tempo, debug]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlphttp/loki] #[otlphttp/loki, debug]