server:
  http_listen_port: 3200
  grpc_listen_port: 3201

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:3201"

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces