global:
  scrape_interval: 15s

storage:
  tsdb:
    out_of_order_time_window: 30m

otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version

scrape_configs:
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:9999']
