name: 'otel-simple'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    volumes:
      - ./config-otel-collector.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"
      - "9999:9999"
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./config-prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    volumes:
      - ./config-loki.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - observability

  tempo:
   image: grafana/tempo:latest
   restart: unless-stopped
   command: -config.file=/etc/tempo/config.yaml
   volumes:
     - ./config-tempo.yaml:/etc/tempo/config.yaml:ro
     - tempo-storage:/var/tempo
   ports:
     - "3200:3200"
     - "4317:4317"
   networks:
     - observability

volumes:
  grafana-storage:
  loki-storage:
  tempo-storage:

networks:
  observability:
    driver: bridge
